### ISSUE TITLE
Change autoappended "-userdev" to "-userdev3"

### ISSUE THREAD

**Issue by ZaneMCXVII** [anatawa12/ForgeGradle-2.3#84]
I'm trying to write a Forge 1.12.2 mod using this version of ForgeGradle and it is unable to get `https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2859/forge-1.12.2-14.23.5.2859-userdev.jar`. 

While this file indeed doesn't exist, `https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2859/forge-1.12.2-14.23.5.2859-userdev3.jar` however does, so I think it would be nice if you could change it from appending `-userdev` to the end of the version name to append `-userdev3`, or have it configurable by the user.

**Comment by anatawa12** [comment]
To use userdev3, please use officially released ForgeGradle 3.0 or later.
I totally recommend you to use FG 5.x with gradle 7.x to write Forge 1.12.2 mods.

The userdev'3' is the userdev for new, versatile userdev system since FG 3.0. That's incompatible with FG 2.x or older so you cannot use it with this version of FG.

**Comment by ZaneMCXVII** [comment]
Problem: It seems like I need FG2 to develop with CodeChickenLib as a dependency.

**Comment by anatawa12** [comment]
If you need to use FG2, please use older forge versions that have -userdev package. It's too hard to implement userdev3 support.

**Comment by anatawa12** [comment]
AFAIK, 2847. later version may supports FG 2 but IDK, Sorry
